### ISSUE TITLE
How do you build on windows?

### ISSUE THREAD

**Issue by hichew52** [ChenThread/fromage#2]
title

**Comment by EGAMatsu** [comment]
whats your issue rn

**Comment by iamgreaser** [comment]
Short answer: You don't.

If you find a way to do this which doesn't involve building this in a Linux VM then feel free to let us know. Otherwise, set up a Linux VM and build it there.

We will not be providing instructions on how to set up a Linux VM, instead we will point out the two things you're probably looking for: VirtualBox, and an Ubuntu ISO.
